### PR TITLE
Initial commit for French localization

### PR DESCRIPTION
**Pull request by damienmathe**
- Added: _locales/fr/messages.json
- Modified: src/commom/moments.ts

### CODE REVIEW

**Comment by damienmathe** [comment]
Hi,

Here is the French localization for the extension.

I have a somewhat limited knowledge of Git, I'm wondering if I did something wrong since there's a check failure…

Regards,

Damien

**Comment by seansfkelley** [comment]
Hey, thanks for taking the time to do this! You didn't do anything wrong, you were just using an outdated version of the English text so you were missing a few translations, which is what the check was complaining about. I don't know if you can see the check results, so I don't know if you have a list of the missing translations, but you can also get at them by merging master into your branch and then running

```
./scripts/diff-messages fr
```

and it'll give you a bunch of JSON to paste at the bottom of your file for the translations you've missed.

I don't know what your intent is with closing this pull request -- but I would love to have a French translation!

**Comment by damienmathe** [comment]
Sorry! It was just me misunderstanding things. As I said, I'm a newbie and still have a lot to learn about GIthub, and seeing the errors just led me to think that there was a problem with the way I did my pull request, and I believed that closing it would "clean" things.

I checked the English version and you were right, some lines were missing. I started the translation a while ago, indeed.

I would be glad to try again! What would you like me to do? Reopen the request, or try a new one?

Sorry if I look like a total noob, but that's what I am right now!

Regards,

Damien

**Comment by seansfkelley** [comment]
You can reopen this pull request or start a new one, whichever is easiest for you. Let me know if you have any more questions!

**Comment by damienmathe** [comment]
I think I'm going to open a new request. But before I proceed, do you think it's best that I merge the branch (I named it "loc_fr") which contains the translation with master? Or can I leave it as it is? I believe the translation is "good to go" but if it is needed to correct some errors in the future, having a dedicated branch is a better option, right?

**Comment by seansfkelley** [comment]
> but if it is needed to correct some errors in the future, having a dedicated branch is a better option

Yeah, you can't really do any kind of development easily without keeping your work on a branch.

If you merge from master into `loc_fr`, you can reopen this pull request using the button below this comment thread. That's the simplest thing to do, and merging from master will bring in any changes you have to handle as well. Just remember to merge from "upstream" master (my repo) not your own master (unless you know it's up to date with mine).

You can also run the tests using `yarn test` (after following the [installation instructions](https://github.com/seansfkelley/synology-download-manager#development)) which should tell you which translations you're missing and which ones you've provided that are no longer used.

**Comment by damienmathe** [comment]
I've reopened the pull request after successfully merging. Got errors again (sorry) but I'm leaving it open, and am waiting for your feedback :-)

I could not test with `yarn`, it returned me an error with exit code 1. Maybe because I'm on Windows?

**Comment by seansfkelley** [comment]
Alright! Are you able to see the build logs? Here's the output of the failing test:

```
  1) i18n
       other locale messages
         "fr" locale should have a subset of the messages from the default locale:

      AssertionError: expected { Object (Add_and_manage_Download_Station_tasks_on_your_Synology_DiskStation, Download_added, ...) } to contain keys 'Add_and_manage_Download_Station_tasks_on_your_Synology_DiskStation', 'Download_added', 'Download_finished', 'Download_with_DownloadStation', 'Selected_text_is_not_a_valid_URL', 'Failed_to_connect_to_DiskStation', 'Please_check_your_settings', 'eMule_is_not_enabled', 'Use_DSM_to_enable_eMule_downloads', 'Failed_to_add_download', 'URL_must_start_with_one_of_ZprotocolsZ', 'URL_is_empty_or_missing', 'Unexpected_error_please_check_your_settings_and_try_again', 'URL_to_download', 'Download_to', 'default_location', 'Dont_add_a_new_task', 'Cancel', 'Download_the_above_URL_to_the_specified_location', 'Add', 'Loading', 'Expandcollapse_directory', 'Settings_unconfigured', 'The_hostname_username_or_password_are_not_configured', 'Updating', 'Updating_download_tasks', 'Error_updating_tasks', 'Updated_ZtimeZ', 'updating_now', 'Add_download', 'Open_DownloadStation_UI', 'Show_task_display_settings', 'Open_settings', 'Configure_your_hostname_username_and_password_in_settings', 'No_download_tasks', 'Download_tasks_exist_but_none_match_your_filters', 'and_ZcountZ_more_hidden_tasks', 'Remove_download', 'Resume', 'Start_seeding', 'Pause', 'ZpercentZ_ZestimateZ_ZcurrentZ_of_ZtotalZ_at_ZspeedZ', 'ZetaZ_remaining', 'no_estimate', 'ZratioZ_ratio_ZtotalZ_uploaded_at_ZspeedZ', '100_ZtotalZ_downloaded', 'ZstatusZ_ZpercentZ_ZcurrentZ_of_ZtotalZ_downloaded', 'Downloading', 'Completed_uploading', 'Completed_not_uploading', 'Errored', 'Other', 'Order_tasks_by', 'name_AZ', 'name_ZA', 'date_added_newest_first', 'date_added_oldest_first', 'date_completed_newest_first', 'date_completed_oldest_first', '_complete_least_first', '_complete_most_first', 'Badge_shows', 'total_task_count', 'filtered_task_count', 'Connection', 'Please_note_that_QuickConnect_IDs_are_not_currently_supported', 'hostname_or_IP_address', 'Username', 'Password', 'Test_Connection_and_Save', 'Task_Display_Settings', 'Display_these_task_types_in_the_popup_menu', 'Miscellaneous', 'Notify_when_adding_downloads', 'Notify_when_downloads_complete', 'Check_for_completed_downloads_every', 'seconds', 'at_least_15', 'Handle_opening_downloadable_link_types_ZprotocolsZ', 'Debugging_Output', 'Clear_output', 'Cannot_save_settings_This_is_a_bug_please_file_an_issue', 'Testing_connection', 'Testing_connection_this_is_unusually_slow_is_your_NAS_asleep', 'Connection_successful', 'Connection_successful_but_may_interfere_with_existing_DSM_sessions_See_', 'issue_32', '_for_more_details', 'Connection_failure_missing_connection_configuration', 'Connection_failure_likely_wrong_protocol', 'Connection_failure_likely_wrong_hostnameport_no_internet_connection_or_invalid_certificate', 'Connection_failure_timeout_check_your_hostnameport_settings_and_internet_connection', 'Connection_failure_unknown_reason', 'Private_browsing_mode_is_not_currently_supported', 'Unknown_error_displaying_tasks', 'Your_download_tasks_are_not_affected', 'Please_', 'file_a_bug', '_and_include_the_information_below', 'Clear_ZcountZ_Completed_Tasks', 'Clear_tasks_that_are_completed_and_not_currently_uploading', 'Unknown_error', 'Invalid_parameter', 'The_requested_API_does_not_exist', 'The_requested_method_does_not_exist', 'The_requested_version_does_not_support_this_functionality', 'The_logged_in_session_does_not_have_permission', 'Session_timeout', 'Session_interrupted_by_duplicate_login', 'No_such_username_or_incorrect_password', 'Account_disabled', 'Permission_denied', 'Twostep_verification_needed', 'Twostep_verification_failed', 'File_upload_failed', 'Max_number_of_tasks_reached', 'Destination_denied', 'Destination_does_not_exist', 'Invalid_task_ID', 'Invalid_task_action', 'No_default_destination', 'Set_destination_failed', 'File_does_not_exist', 'Invalid_parameter_of_file_operation', 'Unknown_error_of_file_operation', 'System_is_too_busy', 'Invalid_user_does_this_file_operation', 'Invalid_group_does_this_file_operation', 'Invalid_user_and_group_does_this_file_operation', 'Cant_get_usergroup_information_from_the_account_server', 'Operation_not_permitted', 'No_such_file_or_directory', 'Nonsupported_file_system', 'Failed_to_connect_internetbased_file_system_ex_CIFS', 'Readonly_file_system', 'Filename_too_long_in_the_nonencrypted_file_system', 'Filename_too_long_in_the_encrypted_file_system', 'File_already_exists', 'Disk_quota_exceeded', 'No_space_left_on_device', 'Inputoutput_error', 'Illegal_name_or_path', 'Illegal_file_name', 'Illegal_file_name_on_FAT_file_system', 'Device_or_resource_busy', 'No_such_task_of_the_file_operation', 'Loading_directories', 'No_directories', 'Cannot_configure_settings_in_private_browsing', 'Adding_download', 'Adding_ZcountZ_downloads', 'ZcountZ_downloads_added', 'Failed_to_add_ZcountZ_downloads', 'ZsuccessZ_downloads_added_ZfailedZ_failed', 'Try_adding_downloads_individually_andor_checking_your_URLs_or_settings', 'No_downloadable_URLs_provided', and 'Please_be_patient_this_may_take_some_time'
      + expected - actual

         "Completed_not_uploading"
         "Completed_uploading"
         "Configure_your_hostname_username_and_password_in_settings"
         "Connection"
      -  "Connection_failed_Likely_cause_wrong_hostnameport_no_internet_connection_or_invalid_certificate"
      -  "Connection_failed_Likely_cause_wrong_protocol"
      -  "Connection_failed_for_an_unknown_reason"
      -  "Connection_settings_are_not_configured"
      +  "Connection_failure_likely_wrong_hostnameport_no_internet_connection_or_invalid_certificate"
      +  "Connection_failure_likely_wrong_protocol"
      +  "Connection_failure_missing_connection_configuration"
      +  "Connection_failure_timeout_check_your_hostnameport_settings_and_internet_connection"
      +  "Connection_failure_unknown_reason"
         "Connection_successful"
         "Connection_successful_but_may_interfere_with_existing_DSM_sessions_See_"
      -  "Connection_timed_out_Check_your_hostnameport_settings_and_internet_connection"
         "Debugging_Output"
         "Destination_denied"
         "Destination_does_not_exist"
         "Device_or_resource_busy"
--
         "Loading"
         "Loading_directories"
         "Max_number_of_tasks_reached"
         "Miscellaneous"
      -  "No_default_destination_is_set_in_Download_Station_for_this_Synology_user"
      +  "No_default_destination"
         "No_directories"
         "No_download_tasks"
         "No_downloadable_URLs_provided"
         "No_space_left_on_device"
--
         "Twostep_verification_failed"
         "Twostep_verification_needed"
         "URL_is_empty_or_missing"
         "URL_must_start_with_one_of_ZprotocolsZ"
      -  "URLs_to_download_one_per_line"
      +  "URL_to_download"
         "Unexpected_error_please_check_your_settings_and_try_again"
         "Unknown_error"
         "Unknown_error_displaying_tasks"
         "Unknown_error_of_file_operation"
```

This means you have translations for the following unused phrases:

- `Connection_failure_likely_wrong_hostnameport_no_internet_connection_or_invalid_certificate`
- `Connection_failure_likely_wrong_protocol`
- `Connection_failure_missing_connection_configuration`
- `Connection_failure_timeout_check_your_hostnameport_settings_and_internet_connection`
- `Connection_failure_unknown_reason`
- `No_default_destination`
- `URL_to_download`

But you need translations for:

- `Connection_failed_Likely_cause_wrong_hostnameport_no_internet_connection_or_invalid_certificate`
- `Connection_failed_Likely_cause_wrong_protocol`
- `Connection_failed_for_an_unknown_reason`
- `Connection_settings_are_not_configured`
- `Connection_timed_out_Check_your_hostnameport_settings_and_internet_connection`
- `No_default_destination_is_set_in_Download_Station_for_this_Synology_user`
- `URLs_to_download_one_per_line`

I recently rephrased these strings to make them clearer, so it makes sense that yours are out of date.

If you update your translations with these changes, it should be good to go!

**Comment by damienmathe** [comment]
Hi,

I moved everything from my Windows box to my Mac laptop. I was able to to run `yarn test` aaaaaand… yup, the results are pretty similar. I really thought that my fork was up-to-date, but it wasn't.

Since then, my local repo is a bit messed up to my taste: did a merge, tried a rebase… And now I have a change log for almost every single file in the repo (when I should only have two).

I still have a lot to learn about the advanced features of Git, and to be really sure to give you something that's correct (I really, really don't want to waste your time), I'm going to do the following things:

- Close the pull request
- Backup my translation
- Restore my fork so it mirrors your repo
- Add the translation back
- Commit my changes, push them to my fork, and then re-open the pull request

Maybe these extra-steps are not necessary, but as I don't fully understand everything perfectly, I just want to be sure to deliver something that will not require much work from you. That was not the point, to begin with :-)

Cheers,

Damien

**Pull request closed without merging**
